"""
Crop utilities. Reads PRECOMPUTED crop boxes from sobone_crop_boxes.json
(generated by precompute_crop_boxes.py, which runs standalone, no torch).

Deliberately uses PIL/numpy only, NEVER cv2, in this file -- having
opencv-contrib-python's bundled cuDNN loaded in the same process as
torch caused CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH crashes on the
model's first conv2d call, regardless of import order or DataLoader
fork settings (both were tried and ruled out). Simply removing cv2
from any process that also runs the model is the reliable fix.
"""
import json
import numpy as np
from pathlib import Path
from PIL import Image

_CROP_BOXES_PATH = Path(__file__).parent / "sobone_crop_boxes.json"
_crop_boxes_cache = None


def _load_crop_boxes():
    global _crop_boxes_cache
    if _crop_boxes_cache is None:
        with open(_CROP_BOXES_PATH) as f:
            _crop_boxes_cache = json.load(f)
    return _crop_boxes_cache


def get_crop_box_for_sequence(seq_dir: Path, first_rgb_path: Path = None):
    boxes = _load_crop_boxes()
    seq_name = Path(seq_dir).name
    if seq_name not in boxes:
        raise KeyError(
            f"No precomputed crop box for '{seq_name}' -- run "
            f"python -m arthronav.precompute_crop_boxes first"
        )
    return tuple(boxes[seq_name]["box"])


def crop_and_resize(image: np.ndarray, box, target_size, is_depth=False):
    """
    is_depth=True uses NEAREST resampling (avoids inventing fractional
    depth values at the valid/invalid mask boundary); otherwise BILINEAR.
    Accepts uint8 (RGB) or float32 (depth) arrays.
    """
    x0, y0, x1, y1 = box
    cropped = image[y0:y1, x0:x1]

    resample = Image.NEAREST if is_depth else Image.BILINEAR

    if cropped.dtype == np.float32:
        # PIL can't handle float32 directly for resize -> use 'F' mode
        pil_img = Image.fromarray(cropped, mode="F")
        resized = pil_img.resize((target_size, target_size), resample=resample)
        return np.array(resized, dtype=np.float32)
    else:
        pil_img = Image.fromarray(cropped)
        resized = pil_img.resize((target_size, target_size), resample=resample)
        return np.array(resized)
